# OZI-RIS Server Pack - PHP integration for Apache 2.4
# Generated by configure_php.cmd. Do not edit.
# Value: @@PHP_ROOT@@

LoadModule php5_module "@@PHP_ROOT@@/php5apache2_4.dll"

# Point mod_php at the php.ini in the PHP directory so the web SAPI
# loads the same extensions as the CLI.
PHPIniDir "@@PHP_ROOT@@"

<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>
