; OZI-RIS Server Pack - PHP 5.4 configuration (generated by configure_php.cmd)
; Placeholders are expanded at install time.
; Values: @@PHP_ROOT@@, @@TIMEZONE@@, @@MEMORY_LIMIT@@,
;         @@UPLOAD_MAX@@, @@POST_MAX@@

[PHP]

engine = On
short_open_tag = Off
asp_tags = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
serialize_precision = 100
default_charset = "UTF-8"

; PERFORMANCE: reduce filesystem stat() calls (legacy WAMP server parity).
realpath_cache_size = 64k
realpath_cache_ttl = 600

; Enable the required extensions (module 3 requirement).
extension_dir = "@@PHP_ROOT@@\ext"
enable_dl = Off

extension=php_mysqli.dll
extension=php_pdo_mysql.dll
; Legacy mysql_* API required by the MYXSIR application.
extension=php_mysql.dll
extension=php_gd2.dll
extension=php_openssl.dll
extension=php_curl.dll
extension=php_mbstring.dll
extension=php_fileinfo.dll

; Error handling: log everything, show nothing.
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
display_errors = Off
display_startup_errors = Off
log_errors = On
log_errors_max_len = 1024
; Legacy app may read $php_errormsg (track_errors = On).
track_errors = On
error_log = "@@PHP_ROOT@@\logs\php-error.log"

; Resource limits.
memory_limit = @@MEMORY_LIMIT@@
max_execution_time = 300
max_input_time = 300

; File uploads.
file_uploads = On
upload_max_filesize = @@UPLOAD_MAX@@
post_max_size = @@POST_MAX@@
upload_tmp_dir = "@@PHP_ROOT@@\tmp"

; Sessions.
session.save_handler = files
session.save_path = "@@PHP_ROOT@@\tmp"
session.use_cookies = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
; GC ~0.1% of requests (1/1000) - legacy WAMP server parity.
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440

; Date / timezone.
date.timezone = @@TIMEZONE@@

; Paths.
include_path = "."
doc_root =
user_dir =

; Network.
allow_url_fopen = On
default_socket_timeout = 60

; Other hardening.
expose_php = Off
max_input_vars = 10000
variables_order = "GPCS"
register_argc_argv = Off
auto_globals_jit = On

[mail function]
SMTP = localhost
smtp_port = 25

[mysql]
mysql.allow_local_infile = On
mysql.allow_persistent = On
mysql.cache_size = 2000
mysql.max_persistent = -1
mysql.max_links = -1
mysql.connect_timeout = 60
mysql.trace_mode = Off

[mysqli]
mysqli.max_persistent = -1
mysqli.max_links = -1
mysqli.cache_size = 2000
mysqli.default_port = 3306
mysqli.reconnect = Off

[mbstring]
mbstring.language = Neutral
